M48
; DRILL file {KiCad (6.0.0)} date Mon Mar  7 15:46:15 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-07T15:46:15+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X127.348Y-97.037
X127.348Y-101.437
T2
X126.873Y-79.552
X165.608Y-79.552
X165.608Y-106.222
T0
M30
